
<?php
require_once 'vendor/autoload.php';

// Don't set headers initially - set them only on success
$error_response = function($message) {
    http_response_code(500);
    header('Content-Type: application/json');
    echo json_encode(['error' => $message]);
    exit;
};

try {
    // Get POST data
    $input = file_get_contents('php://input');
    $data = json_decode($input, true);

    if (!$data || !isset($data['fullName']) || !isset($data['letter'])) {
        $error_response('Missing required data for PDF generation');
    }

    $fullName = trim($data['fullName']);
    $letter = trim($data['letter']);

    // Create PDF
    $pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
    
    // Set document information
    $pdf->SetCreator('RefundPro - Professional Refund Letters');
    $pdf->SetAuthor($fullName);
    $pdf->SetTitle('Professional Refund Request Letter');
    $pdf->SetSubject('Refund Request');
    
    // Remove default header/footer
    $pdf->setPrintHeader(false);
    $pdf->setPrintFooter(false);
    
    // Set margins
    $pdf->SetMargins(20, 20, 20);
    $pdf->SetAutoPageBreak(TRUE, 20);
    
    // Add a page
    $pdf->AddPage();
    
    // Set font for header
    $pdf->SetFont('helvetica', 'B', 16);
    $pdf->SetTextColor(37, 99, 235);
    $pdf->Cell(0, 10, 'Professional Refund Request Letter', 0, 1, 'C');
    $pdf->Ln(10);
    
    // Set font for content
    $pdf->SetFont('helvetica', '', 11);
    $pdf->SetTextColor(0, 0, 0);
    
    // Add letter content
    $letterLines = explode("\n", $letter);
    foreach ($letterLines as $line) {
        $line = trim($line);
        if (empty($line)) {
            $pdf->Ln(4);
        } else {
            $pdf->MultiCell(0, 6, $line, 0, 'L', false, 1);
            $pdf->Ln(2);
        }
    }
    
    // Add footer
    $pdf->Ln(10);
    $pdf->SetFont('helvetica', 'I', 9);
    $pdf->SetTextColor(100, 100, 100);
    $pdf->Cell(0, 5, 'Generated by RefundPro', 0, 1, 'C');
    $pdf->Cell(0, 5, 'Date: ' . date('F j, Y'), 0, 1, 'C');
    
    // Generate PDF content first
    $pdfContent = $pdf->Output('', 'S');
    
    // Set headers for successful PDF download (compatible with IDM and other download managers)
    header('Content-Type: application/pdf');
    header('Content-Description: File Transfer');
    header('Content-Disposition: attachment; filename="premium_refund_letter_' . date('Y-m-d') . '.pdf"');
    header('Content-Length: ' . strlen($pdfContent));
    header('Cache-Control: private, must-revalidate, post-check=0, pre-check=0, max-age=1');
    header('Pragma: public');
    header('Expires: Sat, 26 Jul 1997 05:00:00 GMT');
    header('Last-Modified: ' . gmdate('D, d M Y H:i:s') . ' GMT');
    header('Content-Transfer-Encoding: binary');
    
    // Output PDF
    echo $pdfContent;

} catch (Exception $e) {
    $error_response('PDF generation failed: ' . $e->getMessage());
}
?>
