
<?php
require_once 'vendor/autoload.php';

header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="refund_letter.pdf"');

try {
    // Get POST data
    $input = file_get_contents('php://input');
    $data = json_decode($input, true);

    if (!$data || !isset($data['fullName']) || !isset($data['letter'])) {
        throw new Exception('Missing required data for PDF generation');
    }

    $fullName = trim($data['fullName']);
    $letter = trim($data['letter']);

    // Create PDF
    $pdf = new TCPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
    
    // Set document information
    $pdf->SetCreator('RefundPro - Professional Refund Letters');
    $pdf->SetAuthor($fullName);
    $pdf->SetTitle('Professional Refund Request Letter');
    $pdf->SetSubject('Refund Request');
    
    // Remove default header/footer
    $pdf->setPrintHeader(false);
    $pdf->setPrintFooter(false);
    
    // Set margins
    $pdf->SetMargins(20, 20, 20);
    $pdf->SetAutoPageBreak(TRUE, 20);
    
    // Add a page
    $pdf->AddPage();
    
    // Set font for header
    $pdf->SetFont('helvetica', 'B', 16);
    $pdf->SetTextColor(37, 99, 235);
    $pdf->Cell(0, 10, 'Professional Refund Request Letter', 0, 1, 'C');
    $pdf->Ln(10);
    
    // Set font for content
    $pdf->SetFont('helvetica', '', 11);
    $pdf->SetTextColor(0, 0, 0);
    
    // Add letter content
    $letterLines = explode("\n", $letter);
    foreach ($letterLines as $line) {
        $line = trim($line);
        if (empty($line)) {
            $pdf->Ln(4);
        } else {
            $pdf->MultiCell(0, 6, $line, 0, 'L', false, 1);
            $pdf->Ln(2);
        }
    }
    
    // Add footer
    $pdf->Ln(10);
    $pdf->SetFont('helvetica', 'I', 9);
    $pdf->SetTextColor(100, 100, 100);
    $pdf->Cell(0, 5, 'Generated by RefundPro', 0, 1, 'C');
    $pdf->Cell(0, 5, 'Date: ' . date('F j, Y'), 0, 1, 'C');
    
    // Output PDF
    $pdf->Output('refund_letter_' . date('Y-m-d') . '.pdf', 'D');

} catch (Exception $e) {
    http_response_code(500);
    header('Content-Type: application/json');
    echo json_encode(['error' => 'PDF generation failed: ' . $e->getMessage()]);
}
?>
